services:
  ver3-proxy:
    build: ./nginx/
    restart: always
    container_name: ver3-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    networks:
      - ver3-bridge
  ver3-webserver:
    build: ./backend/
    restart: always
    container_name: ver3-webserver
    volumes:
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - ver3-bridge


networks:
  ver3-bridge:
    driver: bridge
