upstream app{
      server ver2-webserver:8080;
}

server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            fastcgi_pass  app;

            fastcgi_param Host $host;
            fastcgi_param X-Real-IP $remote_addr;
            fastcgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
            fastcgi_param X-Forwarded-Proto $scheme;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
}